### ISSUE TITLE
On nodes that have been connected to the new server curl is broken.

### ISSUE THREAD

**Issue by pjb304** [fruit-testbed/fruitos#6]
When I was setting up the dns updates on the new server I connected nodes pi9fec85 and pif2dbec to it.

These are now back connecting to the old server and have valid tunnels, however, the agent is still reporting them as being down.  I think this is because curl is now broken.

```
pif2dbec:~# curl http://google.co.uk
Error relocating /usr/bin/curl: curl_mime_type: symbol not found
Error relocating /usr/bin/curl: curl_mime_data: symbol not found
Error relocating /usr/bin/curl: curl_mime_data_cb: symbol not found
Error relocating /usr/bin/curl: curl_mime_name: symbol not found
Error relocating /usr/bin/curl: curl_mime_encoder: symbol not found
Error relocating /usr/bin/curl: curl_mime_headers: symbol not found
Error relocating /usr/bin/curl: curl_mime_init: symbol not found
Error relocating /usr/bin/curl: curl_mime_filedata: symbol not found
Error relocating /usr/bin/curl: curl_mime_free: symbol not found
Error relocating /usr/bin/curl: curl_mime_filename: symbol not found
Error relocating /usr/bin/curl: curl_mime_subparts: symbol not found
Error relocating /usr/bin/curl: curl_mime_addpart: symbol not found
```

**Comment by herry13** [comment]
@pjb304 Awos Ali has reported a similar thing a couple months ago. It seems there's something wrong with package `libcurl`.  Please could you try to re-install the package, perhaps by invoking `apk fix libcurl`?

**Comment by pjb304** [comment]
I've previously tried 
```
apk del curl
apk add curl
```
without success.

Here's the ouput of my attempt just now
```
pi9fec85:~# apk fix libcurl
(1/1) Reinstalling libcurl (7.55.0-r0)
OK: 146 MiB in 74 packages
pi9fec85:~# curl http://google.co.uk
Error relocating /usr/bin/curl: curl_mime_type: symbol not found
Error relocating /usr/bin/curl: curl_mime_data: symbol not found
Error relocating /usr/bin/curl: curl_mime_data_cb: symbol not found
Error relocating /usr/bin/curl: curl_mime_name: symbol not found
Error relocating /usr/bin/curl: curl_mime_encoder: symbol not found
Error relocating /usr/bin/curl: curl_mime_headers: symbol not found
Error relocating /usr/bin/curl: curl_mime_init: symbol not found
Error relocating /usr/bin/curl: curl_mime_filedata: symbol not found
Error relocating /usr/bin/curl: curl_mime_free: symbol not found
Error relocating /usr/bin/curl: curl_mime_filename: symbol not found
Error relocating /usr/bin/curl: curl_mime_subparts: symbol not found
Error relocating /usr/bin/curl: curl_mime_addpart: symbol not found
```

As you can see there's no change

**Comment by herry13** [comment]
I'll ssh to the box this afternoon to check it out.

**Comment by herry13** [comment]
```
pi9fec85:~# apk del curl libcurl qemu
pi9fec85:~# apk add curl qemu
pi9fec85:~# curl
curl: try 'curl --help' or 'curl --manual' for more information
```
@pjb304 it's working again now.

Honestly, the cause is still unknown for me. Hopefully it will not happen again on the next release which uses a later version of curl.

_note: qemu depends on libcurl so I had to remove and install as well_

**Comment by pjb304** [comment]
I've just had to do this again on  pi9fec85 which is working happily again.

pif2dbec however is failing to reinstall

```
pif2dbec:~# apk add curl qemu
(1/2) Installing libcurl (7.56.0-r0)
ERROR: libcurl-7.56.0-r0: temporary error (try again later)
(2/2) Installing curl (7.56.0-r0)
ERROR: curl-7.56.0-r0: temporary error (try again later)
2 errors; 145 MiB in 72 packages
```
My other node might not have come back since I moved house - so I'll have a look at that this evening

**Comment by herry13** [comment]
The latest OS has been released at https://fruit-testbed.org/os/edge/releases/armhf/. I think this version will fix this issue. More details of new features provided by this new version are available at https://github.com/fruit-testbed/fruitos/issues/3

However, the web UI has not finished yet. That's the main reason I haven't deployed it on all nodes, only few nodes of mine and @wajdihajji.
