### ISSUE TITLE
welcome message on 0.3.0

### ISSUE THREAD

**Issue by pjb304** [fruit-testbed/fruitos#9]
The welcome message shown when logging into a 0.3.0 image says ```FruitOS v0.2.0```

This can be seen on pi61d8b384

**Comment by pjb304** [comment]
Also observed on pieade592 (which is a v1 pi)

**Comment by herry13** [comment]
Fixed in commit https://github.com/fruit-testbed/apks/commit/61ab60ecbd0510effbedbba845d2282d5c6b38a3#diff-4751f4f4c6aec6106d82d7d71d0a2a46. This will be shipped in FruitOS version 0.4.0.
